plugins {
	id 'fabric-loom' version '1.14-SNAPSHOT'
	id 'maven-publish'
}

version = '1.0.6-fabric-1.21.11'
group = 'rip.ysm'

base {
	archivesName = 'better-player-model'
}

repositories {
    maven { url "https://maven.quiltmc.org/repository/release" }
	maven { url "https://maven.terraformersmc.com/releases/" }
    maven { url "https://maven.architectury.dev/" }
    maven { url "https://jitpack.io" }
    maven { url "https://maven.ladysnake.org/releases" }
    maven { url "https://www.cursemaven.com" }
    maven { url "https://libraries.minecraft.net/" }
    maven { url "https://maven.fabricmc.net/" }
    mavenCentral()
}

def ccaVersion = "7.3.1"

dependencies {
	minecraft "com.mojang:minecraft:1.21.11"
	mappings loom.layered() {
        officialMojangMappings()
    }
    
	modImplementation "net.fabricmc:fabric-loader:0.18.1"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.141.4+1.21.11"
    
    modImplementation "dev.architectury:architectury-fabric:19.0.1"
    include "dev.architectury:architectury-fabric:19.0.1"
    implementation "dev.architectury:architectury-injectables:1.0.11"
    
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-api:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-api:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-base:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-block:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-chunk:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-entity:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-item:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-level:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-scoreboard:${ccaVersion}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-world:${ccaVersion}"
    modImplementation "curse.maven:forge-config-api-port-547434:7337130"
    include "curse.maven:forge-config-api-port-547434:7337130"
    implementation "com.electronwill.night-config:core:3.8.3"
    include "com.electronwill.night-config:core:3.8.3"
    implementation "com.electronwill.night-config:toml:3.8.3"
    include "com.electronwill.night-config:toml:3.8.3"
    modCompileOnly "com.terraformersmc:modmenu:15.0.0"
    
    implementation "com.github.TartaricAlkaline:ImageStream:-SNAPSHOT"
    include "com.github.TartaricAlkaline:ImageStream:-SNAPSHOT"

    implementation "com.github.luben:zstd-jni:1.5.7-8"
    include "com.github.luben:zstd-jni:1.5.7-8"

    implementation 'net.java.dev.jna:jna:5.14.0'
    include 'net.java.dev.jna:jna:5.14.0'
    
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
    it.options.encoding = "UTF-8"
    it.exclude("net/minecraft/**")
    it.exclude("net/fabricmc/**")
    it.exclude("com/mojang/**")
    it.exclude("dev/architectury/**")
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(Jar).configureEach {
    exclude("net/minecraft/**")
    exclude("net/fabricmc/**")
    exclude("com/mojang/**")
    exclude("dev/architectury/**")
}

loom {
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "better_player_model.refmap.json"
    }
}

tasks.register('runTestParser', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.elfmcys.yesstevemodel.client.TestParser'
}
