# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# FORCING JAVA 21
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.11.10-hotspot

# Mod properties
mod_version = 1.1.2-pure-java-fabric-1.21.11
maven_group = rip.ysm
archives_name = better-player-model-pure-java

# Minecraft properties
minecraft_version = 1.21.11

# Dependencies
fabric_loader_version = 0.18.1
fabric_api_version = 0.141.4+1.21.11


